CREATE TABLE character (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(40),
    species         VARCHAR(20),
    starting_level  INTEGER NOT NULL,
    special_ability VARCHAR(60) NOT NULL,
    bio             VARCHAR(280),
    creation_date   DATE NOT NULL,

    CONSTRAINT pk_character PRIMARY KEY (id)

    );

INSERT INTO character (name, species, starting_level, special_ability, bio, creation_date)
VALUES
    ('John Doe', 'HUMAN', 10, 'Super Strength', 'John is a skilled fighter with enhanced strength and agility.', '2023-08-01'),
    ('Xara', 'CYBORG', 25, 'Laser Vision', 'A hybrid warrior, part human, part machine, Xara possesses advanced optical enhancements.', '2022-05-15');
